# Generated by Django 3.2.7 on 2021-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='number',
            field=models.IntegerField(default=5),
        ),
    ]
