# Generated by Django 3.2.7 on 2021-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20211117_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
